server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      routes:
        - id: user-service-docs
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**
        - id: product-service-docs
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/products/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/products/**
        - id: cart-service-docs
          uri: ${CART_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/carts/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: cart-service
          uri: ${CART_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/carts/**
        - id: order-service-docs
          uri: ${ORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/orders/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/orders/**
        - id: payment-service-docs
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/payments/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/payments/**
        - id: notification-service-docs
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/notifications/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/notifications/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /api/users/v3/api-docs
      - name: product-service
        url: /api/products/v3/api-docs
      - name: cart-service
        url: /api/carts/v3/api-docs
      - name: order-service
        url: /api/orders/v3/api-docs
      - name: payment-service
        url: /api/payments/v3/api-docs
      - name: notification-service
        url: /api/notifications/v3/api-docs


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
