server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/carts/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/notifications/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
