server:
  port: 8083

spring:
  application:
    name: cart-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce_cart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
